### ISSUE TITLE
待机状态下cpu一直占用28%-30%

### ISSUE THREAD

**Issue by BrunuhVille** [Thanf-code/Autobuild-Newifi_D2#4]
你好，我刷了这个固件，待机状态下cpu一直占用28%-30%
请问有相似的情况吗

**Comment by Thanf-code** [comment]
> 你好，我刷了这个固件，待机状态下cpu一直占用28%-30% 请问有相似的情况吗

自从9月中旬源码更新后 就一直有这个问题。应该是源码更新后无人适配联发科芯片导致的

**Comment by Thanf-code** [comment]
> 你好，我刷了这个固件，待机状态下cpu一直占用28%-30% 请问有相似的情况吗

最新固件  没得这个问题
